config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :users

  root 'products#index'

  resources :products
  devise_scope :user do
    authenticate :user do
      resources :categories, only: [:create, :destroy, :edit, :update, :new]
      patch 'bulk', to: 'categories#bulk_update', as: 'bulk'
    end
  end

  get 'categories/:id', to: "categories#show", as: "category_show"

  post "/cart", to: "carts#add_to_cart", as: "cart_add"
  get "/cart", to: "carts#view_cart", as: "cart"
  patch "/cart", to: "carts#remove_from_cart", as: "cart_remove_item"

  resources :orders, only: [:create, :new, :show]

  devise_scope :user do
    authenticate :user do
      get "/admin", to: "admins#manage", as: :admin
    end
  end

end

app/views/admins/manage.html.erb
<p class="lead">Product Management</p>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Actions</th>
  </tr>
  
  <%- @products.each do |p| %>
    <tr>
      <td> <%=p.title %> </td>
        <td>
          <%=link_to("Edit Product", edit_product_path(p), class: "btn btn-default")  %>
          <%=link_to("Delete Product", product_path(p), method: :delete, class: "btn btn-default")  %>
        </td>
    </tr>
  <% end %>
</table>

<%=link_to("New Product", new_product_path, class: "btn btn-default")%>

<br>
<br>

<p class="lead">Category Management</p>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Actions</th>
  </tr>
  
  <%- @categories.each do |cat| %>
    <tr>
      <td> <%=cat.title %> </td>
      <td>
        <%=link_to("Edit Category", edit_category_path(cat), class: "btn btn-default") %>
        <%=link_to("View Products", products_path(search_no_subcats: cat.id), class: "btn btn-default") %>
        <%=link_to("Delete Category", category_path(cat), method: :delete, class: "btn btn-default") %>
      </td>
    </tr>
  <% end %>
</table>

<%=link_to("New Category", new_category_path, class: "btn btn-default")%>

<p class="lead">Order Management</p>
<table class="table">
  <tr>
    <th>ID</th>
    <th>Customer</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>
  
  <%- @orders.each do |o| %>
    <tr>
      <td> <%=o.id %> </td>
      <td> <%=o.customer %> </td>
      <td> <%=o.total %> </td>
      <td>
        <%=link_to("View Order", order_path(o), class: "btn btn-default") %>
      </td>
    </tr>
  <% end %>
</table>