config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :users

  root 'products#index'

  resources :products
  devise_scope :user do
    authenticate :user do
      resources :categories, only: [:create, :destroy, :edit, :update, :new]
      patch 'bulk', to: 'categories#bulk_update', as: 'bulk'
    end
  end

  get 'categories/:id', to: "categories#show", as: "category_show"

  post "/cart", to: "carts#add_to_cart", as: "cart_add"
  get "/cart", to: "carts#view_cart", as: "cart"
  patch "/cart", to: "carts#remove_from_cart", as: "cart_remove_item"

  resources :orders, only: [:create, :new, :show]

  devise_scope :user do
    authenticate :user do
      get "/admin", to: "admins#manage", as: :admin
    end
  end

end

app/views/shared/_drop_down_categories.html.erb
<ul>
  <%- categories.each do |category| %>
    <%- if category.subcategories.count == 0 %>
      <li>
        <%= link_to category.title, category_show_path(category) %>
      </li>
    <%- else %>
        <li>
          <%= link_to category.title, products_path(category) %>
          <%= render partial: "shared/drop_down_categories", locals: {level: "dropdown-menu", categories: category.subcategories} %>
        </li>
    <% end %>
  <% end %>
<ul>

app/views/shared/_products.html.erb
<%- @products.each do |product| %>
  <%=cache(@product) do%>
    <h1><%= truncate(product.title, length: 40) %></h1>
    <%- product.pictures.each do |p| %>
      <%= image_tag p.image.thumb.url %>
    <% end %>
    <br>
    <%= truncate(product.description, length: 50) %>
    <br>
    <%= link_to 'View Product', product_path(product), class: "btn btn-success"%>
    <%=link_to("Add to Cart", cart_add_path(product_id: product.id), method: :post, class: "btn btn-warning") %>
    <p></p>
    <hr>
  <% end %>
<% end %>