config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :users

  root 'products#index'

  resources :products
  devise_scope :user do
    authenticate :user do
      resources :categories, only: [:create, :destroy, :edit, :update, :new]
      patch 'bulk', to: 'categories#bulk_update', as: 'bulk'
    end
  end

  get 'categories/:id', to: "categories#show", as: "category_show"

  post "/cart", to: "carts#add_to_cart", as: "cart_add"
  get "/cart", to: "carts#view_cart", as: "cart"
  patch "/cart", to: "carts#remove_from_cart", as: "cart_remove_item"

  resources :orders, only: [:create, :new, :show]

  devise_scope :user do
    authenticate :user do
      get "/admin", to: "admins#manage", as: :admin
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :products
  belongs_to :parent_category, class_name: "Category"
  has_many :subcategories, class_name: "Category", foreign_key: "parent_category_id"
  validates :title, presence: true
  validates :title, uniqueness: {message: "A category with this name already exists"}

  def update_products(category_id)
    self.products.each do |p|
      p.update_attributes(category_id: (category_id.present? ? category_id : nil))
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Permissions
  before_action :check_privileges, only: [:create, :new, :update, :edit, :destroy]
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash.notice = "A new category has been successfully created"
      redirect_to admin_path
    else
      flash.alert = @category.errors.full_messages.join('. ')
      render :new
    end
  end

  def show
    @products = Product.where(category: @category)
  end

  def update
    if check_dependencies(@category, params[:category][:parent_category_id])
      if @category.update_attributes(category_params)
        flash.notice = "The category has been updated"
        redirect_to admin_path
      else
        flash.error = @category.errors.full_messages.join('. ')
        render :edit
      end
    else
      redirect_to edit_category_path(@category)
    end
  end

  def edit
  end

  def destroy
    if !@category.subcategories.any? && !@category.products.any?
      @category.destroy
      flash.notice = "The category has been successfully removed"
      redirect_to admin_path
    else
      flash.alert = "The category cannot be deleted as it has dependent products or subcategories. Please, move dependent entities to other categories first using Edit action."
      redirect_to admin_path
    end
  end

  def bulk_update
    current_category = Category.find(params[:current_category].to_i)
    if current_category.update_products(params[:category_new].to_i)
      flash.notice = "Products have been sucessfully moved to another category"
    else
      flash.alert = @category.errors.full_messages.join('. ')
    end
    redirect_to admin_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :parent_category_id)
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end

  def check_dependencies(previous_cat, new_cat)
    if previous_cat.subcategories.any? || previous_cat == new_cat
      flash.alert = "Category cannot be updated to use the selected entity as its parent. Category must not be a parent to itself. Any dependent subcategory (immediate or indirect relation) cannot act as a parent to a higher level predecessor to avoid an infinite loop. Please, move all child categories from this category before proceeding. Update is not available for categories with subcategories in place."
      false
    else
      true
    end
  end

end

app/views/categories/_categories.html.erb
<div>
  <%= form_for :category, url: url, method: method, html: { class: "form-group"} do |f| %>

    <div class="form-group">
      <%= f.label :slug, "Category URL" %><br>
      <%= f.text_field :slug, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :title, "Category title" %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :parent_category_id, "Parent category" %><br>
      <%= f.collection_select :parent_category_id, Category.all, :id, :title, include_blank: "No parent (make it root category)",  class: "form-control" %>
    </div>    
   
    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default"%>
      <%= link_to 'Back', admin_path, class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render partial: "categories", locals: {url: category_path, method: :patch} %>

<p class="lead">Depenencies Management</p>

<%- if @category.products.any?%>
  <p>This category has no dependent products.</p>
<%- else %>
  <p>This category has the following products:</p>
  <%=link_to("View Products", products_path(category_search: @category.id), class: "btn btn-default") %>

  <%= form_tag bulk_path(current_category: @category), method: :patch do %>
    <%= label_tag :category_new, "Link these products to another category"%>
    <%=select_tag :category_new, options_from_collection_for_select(Category.all, "id", "title"), include_blank: "No category"%>
    <%= submit_tag("Update", class: "btn btn-default") %>
  <% end %>
<% end %>
<br>
<p><strong>To remove this category, please select "No parent" in the parent category selection and migrate products from this category to another one, then click "Remove Category" in the Admin Panel.<strong></p>

app/views/categories/new.html.erb
<%=render partial: "categories", locals: {url: categories_path, method: :post} %>

app/views/categories/show.html.erb
<%= render partial: "shared/products" %>