config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :users

  root 'products#index'

  resources :products
  devise_scope :user do
    authenticate :user do
      resources :categories, only: [:create, :destroy, :edit, :update, :new]
      patch 'bulk', to: 'categories#bulk_update', as: 'bulk'
    end
  end

  get 'categories/:id', to: "categories#show", as: "category_show"

  post "/cart", to: "carts#add_to_cart", as: "cart_add"
  get "/cart", to: "carts#view_cart", as: "cart"
  patch "/cart", to: "carts#remove_from_cart", as: "cart_remove_item"

  resources :orders, only: [:create, :new, :show]

  devise_scope :user do
    authenticate :user do
      get "/admin", to: "admins#manage", as: :admin
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="blog-masthead" id="DIV_1_1">
    <div class="container" id="DIV_2_2">
      <nav class="navbar navbar-inverse">
        <div class="container" id="DIV_1">
          <div class="navbar-header" id="DIV_2">
            <a class="navbar-brand" href= <%=root_path%> id="A_8">E-commerce</a>
          </div>
          <div class="nav navbar-form navbar-right" id="button-header-group">
            <%= link_to("View Cart", cart_path, method: 'get', class: "btn btn-default") %>
            <%- if current_user %> 
              <%= link_to("Sign Out", destroy_user_session_path, method: 'delete', class: "btn btn-default blog-nav-item") %>
              <%= link_to("Edit Account", edit_user_registration_path, class: "btn btn-default")  %>
              <%- if current_user.is_admin %>
                <%=link_to("New Product", new_product_path, class: "btn btn-default")  %>
                <%=link_to("Admin Panel", admin_path, class: "btn btn-default")  %>
              <% end %>
            <%- else %>
              <%= link_to("Sign In", new_user_session_path, method: 'get', class: "btn btn-default") %>
              <%= link_to("Create New Account", new_user_registration_path, method: 'get', class: "btn btn-default") %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
  </div>

  <div class="container">
    <div class="col-md-9">
      <div id="flash_placeholder">
        <%- if flash[:alert] %>
          <div id='errors' class="alert alert alert-danger">
            <%= flash[:alert] %>
            <br></br>
          </div>
        <% end %>

        <%- if flash[:notice] %>
          <div id='notices' class="notice alert alert-info">
            <%= flash[:notice] %>
            <br></br>
          </div>
        <% end %>
      </div>
  

      <%= yield %>
    </div>

    <div class="col-md-3 blog-sidebar" id="DIV_1">
      <div class="sidebar-module sidebar-module-inset" id="DIV_2">
        <h3 id="H4_3">About</h3>
        <p id="P_4"><h3><small>Bringing world's best goods with a few keystrokes. </small></p>
      </div>

      <div class="sidebar-module" id="DIV_33">
        <p> <h3>Search</h3> </p>    
      </div>

      <div>
        <%= form_tag products_path, method: :get do %>
          <%= text_field_tag(:query, params[:query], placeholder: 'Search query', class: "form-control") %>
          <br>
          <p>Scope the search to the following categories:</p>
          <%= label_tag :category_search, "Categories"%>
          <%=select_tag :category_search, options_from_collection_for_select(Category.all, "id", "title"), include_blank: "All categories", class: "form-control" %>
          <%= submit_tag("Find", class: "btn btn-default") %>
        <% end %>
      </div>
      <div>
        <br>
        <p>Browse goods by category</p>
        <ul>
          <%- Category.order("title asc").each do |category|%>
              <li>
                <%= link_to category.title, category_show_path(category)%>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</body>
</html>